import { Dispatch } from "redux";

export const ACTION_TYPE = {
  CONTACTS_REQUEST_START: "CONTACTS_REQUEST_START",
  CONTACTS_REQUEST_SUCCESS: "CONTACTS_REQUEST_SUCCESS",
  CONTACTS_REQUEST_ERROR: "CONTACTS_REQUEST_ERROR",

  FAVORITES_REQUEST_START: "FAVORITES_REQUEST_START",
  FAVORITES_REQUEST_SUCCESS: "FAVORITES_REQUEST_SUCCESS",
  FAVORITES_REQUEST_ERROR: "FAVORITES_REQUEST_ERROR",

  FAVORITES_ADD_CONTACT_ID: "FAVORITES_ADD_CONTACT_ID",
  FAVORITES_REMOVE_CONTACT_ID: "FAVORITES_REMOVE_CONTACT_ID",

  GROUPS_REQUEST_START: "GROUPS_REQUEST_START",
  GROUPS_REQUEST_SUCCESS: "GROUPS_REQUEST_SUCCESS",
  GROUPS_REQUEST_ERROR: "GROUPS_REQUEST_ERROR",
} as const;

export type ActionType = keyof typeof ACTION_TYPE;

export interface Action<T extends ActionType = ActionType, P = unknown> {
  type: T;
  payload?: P;
}

export type AppDispatch = Dispatch<Action>;
